### ISSUE TITLE
False Positive [app.appsflyer.com]

### ISSUE THREAD

**Issue by markangus2b** [mhxion/pornaway#20]
app.appsflyer.com

The following URL is used to redirect to app in the Play Store.  The Link below is from Weather Underground.  Clicking the Play Store button will result in a block.

Weather Underground app download page
https://www.wunderground.com/download

**Comment by mhxion** [comment]
@markangus2b Thanks for letting me know. Yes it's not a porn site (anymore), although I'm not sure if the site is harmless, it's listed in [Peter Lowe's ad list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext). I will remove it from `porn_sites.txt` and place it in `safe_ads.txt` for now.
